[package]
name = "gdk-common"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
edition = "2018"

[dependencies]
log = "0.4.8"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.3"
backtrace = "0.3"

[dependencies.bitcoin]
version = "0.23"
features = ["use-serde"]